### ISSUE TITLE
A question about data preprocessing

### ISSUE THREAD

**Issue by speedcell4** [sustcsonglin/TN-PCFG#2]
Hi, thanks for sharing the source code.

In the released PTB dataset I found two files named `ptb-train.pickle` and `ptb-train-lpcfg.pickle` respectively. What are the differences between them?

Thanks~

**Comment by sustcsonglin** [comment]
Basically they are the same,  `ptb-train-lpcfg.pickle` contains dependency heads annotations in addition for unsupervised dependency parsing.

**Comment by speedcell4** [comment]
I got it, thank you~
