### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by rubencart** [sustcsonglin/TN-PCFG#8]
The readme states `conda create -n pcfg python=3.7` yet `typing.final` is used below, which was only added in python 3.8.

https://github.com/sustcsonglin/TN-PCFG/blob/844e9c3455b9abfb3858ba49b86f62e1aacc75d6/parser/pcfgs/simple_pcfg.py#L2

**Comment by sustcsonglin** [comment]
Thanks. I've changed the python requirement.
