### ISSUE TITLE
Trained checkpoints

### ISSUE THREAD

**Issue by rubencart** [sustcsonglin/TN-PCFG#9]
Do you happen to have other trained checkpoints than TN-PCFG and NBL-PCFG (like N-PCFG, C-PCFG, SN-PCFG,...) that you could share?

**Comment by sustcsonglin** [comment]
Sorry, I cannot find those checkpoints. It should be very fast to re-train.

**Comment by rubencart** [comment]
OK I managed to retrain them, thanks.
